---
# configure appdynamics ha controller platform service by appdynamics. -----------------------------
- name: upload appd license file to controller nodes
  copy:
    src: ../../../shared/license/appd-controller-license.lic
    dest: "{{ env_vars.appd_home }}/{{ env_vars.appd_platform_home }}/{{ env_vars.appd_platform_product_home }}/controller/license.lic"
    mode: '0644'
    owner: "{{ env_vars.appd_platform_user_name }}"
    group: "{{ env_vars.appd_platform_user_group }}"
  become: yes
  become_user: "{{ env_vars.appd_platform_user_name }}"

- name: create appd controller systemd service file
  template:
    src: templates/appdynamics-controller.service.j2
    dest: /etc/systemd/system/appdynamics-controller.service
    force: yes
    backup: yes

- name: reload systemd manager configuration and enable the controller service
  systemd:
    daemon_reload: yes
    enabled: yes
#   state: started
    name: appdynamics-controller.service
