---
# configure appdynamics events service by appdynamics. ---------------------------------------------
- name: create appd events service systemd service file
  template:
    src: templates/appdynamics-events-service.service.j2
    dest: /etc/systemd/system/appdynamics-events-service.service
    force: yes
    backup: yes

- name: reload systemd manager configuration and enable the events service service
  systemd:
    daemon_reload: yes
    enabled: yes
    name: appdynamics-events-service.service
