---
# tasks file for appdynamics.apm-platform-ha

# create appd user on all remote hosts.
- name: import create appd user task
  include_tasks: create-appduser.yml

# install appdynamics platform services pre-requisites on all remote hosts.
- name: import setup apm platform task
  include_tasks: setup-apm-platform.yml

# install appdynamics enterprise console on master node.
- name: import install appd enterprise console task
  include_tasks: install-appd-enterprise-console.yml
  when: "'enterprise_console' in group_names"

# reduce the default sizing for the appdynamics controller medium profile. [optional]
- name: import reduce default sizing entries task
  include_tasks: reduce-controller-profile.yml
  when: "('enterprise_console' in group_names) and (env_vars.appd_controller_reduced_profile)"

# install appdynamics ha controller via the master node.
- name: import install appd ha controller task
  include_tasks: install-appd-controller.yml
  when: "'enterprise_console' in group_names"

# configure appdynamics ha controller via the master node.
- name: import config appd ha controller task
  include_tasks: config-appd-controller.yml
  when: "'controller' in group_names"

# configure appdynamics controller watchdog service via the master node.
- name: import config appd controller watchdog task
  include_tasks: config-appd-controller-watchdog.yml
  when: "'enterprise_console' in group_names"
