---
# tasks file for appdynamics.apm-platform-ha

# create and configure appd user on all remote hosts. ----------------------------------------------
- name: import create and configure appd user tasks
  include_tasks: create-appduser.yml

# install appdynamics platform services pre-requisites on all remote hosts. ------------------------
- name: import setup apm platform tasks
  include_tasks: setup-apm-platform.yml

# install appdynamics enterprise console on ec node. -----------------------------------------------
- name: import install appd enterprise console tasks
  include_tasks: install-appd-enterprise-console.yml
  when: "'enterprise_console' in group_names"

# reduce the default sizing for the appdynamics controller medium profile. [optional]
- name: import reduce controller default sizing tasks
  include_tasks: reduce-controller-profile.yml
  when: "('enterprise_console' in group_names) and (env_vars.appd_controller_reduced_profile)"

# reduce the default sizing for the appdynamics events service production profile. [optional]
- name: import reduce events service default sizing tasks
  include_tasks: reduce-events-service-profile.yml
  when: "('enterprise_console' in group_names) and (env_vars.appd_events_service_reduced_profile)"

# create appdynamics platform and add user credentials. --------------------------------------------
- name: import create appd platform tasks
  include_tasks: create-appd-platform.yml
  when: "'enterprise_console' in group_names"

# install appdynamics ha controller via the ec node. -----------------------------------------------
- name: import install appd ha controller tasks
  include_tasks: install-appd-controller.yml
  when: "'enterprise_console' in group_names"

# configure appdynamics ha controller on the controller nodes.
- name: import config appd ha controller tasks
  include_tasks: config-appd-controller.yml
  when: "'controller' in group_names"

# configure appdynamics controller watchdog service via the ec node.
- name: import config appd controller watchdog tasks
  include_tasks: config-appd-controller-watchdog.yml
  when: "'enterprise_console' in group_names"

# install appdynamics events service cluster via the ec node. --------------------------------------
- name: import install appd events service cluster tasks
  include_tasks: install-appd-events-service.yml
  when: "'enterprise_console' in group_names"

# configure appdynamics events service cluster on the events service nodes.
- name: import config appd events service cluster tasks
  include_tasks: config-appd-events-service.yml
  when: "'events_service' in group_names"

# install appdynamics eum server on the eum server node. -------------------------------------------
- name: import install appd eum server tasks
  include_tasks: install-appd-eum-server.yml
  when: "'eum_server' in group_names"

# update appdynamics platform configurations. ------------------------------------------------------
- name: import update platform configurations tasks
  include_tasks: update-appd-platform-configurations.yml
  when: "'enterprise_console' in group_names"

# update appdynamics controller configurations. ----------------------------------------------------
- name: import update controller configurations tasks
  include_tasks: update-appd-controller-configurations.yml
  when: "'enterprise_console' in group_names"
