---
- name: install appdynamics cloud platform
  hosts: all
  gather_facts: yes
  any_errors_fatal: yes
  environment:
    appd_platform_user_name: "{{ lookup('env', 'appd_platform_user_name') | default('appduser', true) }}"
    appd_platform_user_group: "{{ lookup('env', 'appd_platform_user_group') | default('appduser', true) }}"

  roles:
    - role: appdynamics.apm-platform-ha
